name: "01-EKS"
on:
  workflow_dispatch:
jobs:
  Plan:
    uses: Kavana1997/AWS_KS_Labs/.github/workflows/aws_tf_plan.yml@main
    with:
      gh_environment: dev
  Apply:
    needs: Plan
    uses: Kavana1997/AWS_KS_Labs/.github/workflows/aws_tf_appy.yml@main
    with:
      gh_environment: dev
